[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "smartgis-tutorial"
authors = [{name = "AproJ", email = "apro@manufaktura.rs"}]
dynamic = ["version", "description"]
